name: CI/Cd AWS S3

on:
  push:
    branches:
      - main
      - feat/NINEDOCS-242-cloudfront-cache-invalidation

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: AWS IAM 사용자 설정
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Yarn 설치
        run: npm install -g yarn

      - name: React Build
        run: |
          yarn install
          yarn build

      - name: s3에 업로드
        # delete 옵션 : 기존에 S3 버킷에 남아있던 파일들 제거한 후 새 파일 업로드
        # 일시적인 끊김이 발생할 수 있으나, CloudFront의 캐싱을 믿어보는걸로..
        run: aws s3 sync build/ s3://${{ vars.S3_BUCKET_NAME }} --delete
      
      - name: 캐시 무력화
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ vars.AWS_CLOUDFRONT_ID }}
          PATHS: "/*"
          AWS_REGION: ${{ vars.AWS_REGION}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
